<?php
// DATABASE
include 'db_conf.php';
if (!isset($_SESSION['username'])){
	echo "<script type='text/javascript'>alert('Login failed');</script>";
	echo ("<script>location.href='login.php'</script>");
	return;
 }
RemoveAllData();

ThemVung($link,"An Giang","3536.7");
ThemVung($link,"Bà Rịa - Vũng Tàu","1989.5");
ThemVung($link,"Bắc Giang","3844");
ThemVung($link,"Bắc Kạn","4859.4");
ThemVung($link,"Bạc Liêu","2468.7");
ThemVung($link,"Bắc Ninh","822.7");
ThemVung($link,"Bến Tre","2360.6");
ThemVung($link,"Bình Định","6050.6");
ThemVung($link,"Bình Dương","2694.4");
ThemVung($link,"Bình Phước","6871.5");
ThemVung($link,"Bình Thuận","7812.9");
ThemVung($link,"Cà Mau","5294.9");
ThemVung($link,"Cần Thơ","1409");
ThemVung($link,"Cao Bằng","6707.9");
ThemVung($link,"Đà Nẵng","1285.4");
ThemVung($link,"Đắk Lắk","13125.4");
ThemVung($link,"Đắk Nông","6515.6");
ThemVung($link,"Điện Biên","9562.9");
ThemVung($link,"Đồng Nai","5907.2");
ThemVung($link,"Đồng Tháp","3377");
ThemVung($link,"Gia Lai","15536.9");
ThemVung($link,"Hà Giang","7914.9");
ThemVung($link,"Hà Nam","860.5");
ThemVung($link,"Hà Nội","3328.9");
ThemVung($link,"Hà Tĩnh","5997.2");
ThemVung($link,"Hải Dương","1656");
ThemVung($link,"Hải Phòng","1523.4");
ThemVung($link,"Hậu Giang","1602.5");
ThemVung($link,"Hoà Bình","4608.7");
ThemVung($link,"Hưng Yên","926");
ThemVung($link,"Khánh Hoà","5217.7");
ThemVung($link,"Kiên Giang","6348.5");
ThemVung($link,"Kon Tum","9689.6");
ThemVung($link,"Lai Châu","9068.8");
ThemVung($link,"Lâm Đồng","9773.5");
ThemVung($link,"Lạng Sơn","8320.8");
ThemVung($link,"Lào Cai","6383.9");
ThemVung($link,"Long An","4492.4");
ThemVung($link,"Nam Định","1651.4");
ThemVung($link,"Nghệ An","16493.7");
ThemVung($link,"Ninh Bình","1390.3");
ThemVung($link,"Ninh Thuận","3358.3");
ThemVung($link,"Phú Thọ","3533.4");
ThemVung($link,"Phú Yên","5060.6");
ThemVung($link,"Quảng Bình","8065.3");
ThemVung($link,"Quảng Nam","10438.4");
ThemVung($link,"Quảng Ngãi","5153");
ThemVung($link,"Quảng Ninh","6102.4");
ThemVung($link,"Quảng Trị","4739.8");
ThemVung($link,"Sóc Trăng","3311.6");
ThemVung($link,"Sơn La","14174.4");
ThemVung($link,"Tây Ninh","4039.7");
ThemVung($link,"Thái Bình","1570");
ThemVung($link,"Thái Nguyên","3531.7");
ThemVung($link,"Thanh Hoá","11131.9");
ThemVung($link,"Thừa Thiên Huế","5033.2");
ThemVung($link,"Tiền Giang","2508.3");
ThemVung($link,"TP Hồ Chí Minh","2095.6");
ThemVung($link,"Trà Vinh","2341.2");
ThemVung($link,"Tuyên Quang","5867.3");
ThemVung($link,"Vĩnh Long","1496.8");
ThemVung($link,"Vĩnh Phúc","1236.5");
ThemVung($link,"Yên Bái","6886.3");
ThemVung($link,"Toàn Quốc","331210");
echo "Hoàn tất cập nhật danh sách vùng";
//--------------------------------------------------------------
ThemDichVu($link,"Âm nhạc");
ThemDichVu($link,"An ninh");
ThemDichVu($link,"Bãi đỗ xe hơi");
ThemDichVu($link,"Bãi đỗ xe máy");
ThemDichVu($link,"Bảng điện tử led");
ThemDichVu($link,"Bảng hiệu, bảng quảng cáo, chữ nổi, kệ trưng bày");
ThemDichVu($link,"Bệnh viện");
ThemDichVu($link,"Bida");
ThemDichVu($link,"Cao Đẳng");
ThemDichVu($link,"Cây cảnh");
ThemDichVu($link,"Cây giống");
ThemDichVu($link,"Chăm sóc cây cảnh");
ThemDichVu($link,"Chăm sóc người già");
ThemDichVu($link,"Chăm sóc sức khỏe tại nhà");
ThemDichVu($link,"Chăm sóc tại gia");
ThemDichVu($link,"Chăm sóc thú cưng");
ThemDichVu($link,"Chỗ ở");
ThemDichVu($link,"Chợ");
ThemDichVu($link,"Công Chứng Tại Nhà");
ThemDichVu($link,"Công ty bảo vệ");
ThemDichVu($link,"Cửa hàng bán đồ lưu niệm");
ThemDichVu($link,"Cửa hàng bán đồ thể thao");
ThemDichVu($link,"Cửa hàng bán hoa");
ThemDichVu($link,"Cửa hàng bánh kẹo");
ThemDichVu($link,"Cửa hàng Điện cơ");
ThemDichVu($link,"Cửa hàng Điện tử gia dụng");
ThemDichVu($link,"Cửa hàng Điện tử văn phòng");
ThemDichVu($link,"Cửa hàng đồ gỗ cũ");
ThemDichVu($link,"Cửa hàng đồ gỗ");
ThemDichVu($link,"Cửa hàng đồng hồ");
ThemDichVu($link,"Cửa hàng giày dép");
ThemDichVu($link,"Cửa hàng két sắt");
ThemDichVu($link,"Cửa hàng mắt kính");
ThemDichVu($link,"Cửa hàng máy quay phim, chụp hình");
ThemDichVu($link,"Cửa hàng mũ bảo hiểm");
ThemDichVu($link,"Cửa hàng mỹ phẩm");
ThemDichVu($link,"Cửa hàng nông nghiệp");
ThemDichVu($link,"Cửa hàng phụ kiện xe hơi");
ThemDichVu($link,"Cửa hàng phụ kiện xe maý");
ThemDichVu($link,"Cửa hàng quần áo");
ThemDichVu($link,"Cửa hàng tạp hóa gia đình");
ThemDichVu($link,"Cửa hàng thiết bị báo động chống trộm");
ThemDichVu($link,"Cửa hàng thú cưng");
ThemDichVu($link,"Cửa hàng thực phẩm thú cưng");
ThemDichVu($link,"Cửa hàng tiện lợi");
ThemDichVu($link,"Cửa hàng trang sức");
ThemDichVu($link,"Cửa hàng và dịch vụ quảng cáo ");
ThemDichVu($link,"Cửa hàng xe đạp");
ThemDichVu($link,"Cửa hàng xe hơi cũ");
ThemDichVu($link,"Cửa hàng xe hơi");
ThemDichVu($link,"Cửa hàng xe máy cũ");
ThemDichVu($link,"Cửa hàng xe máy");
ThemDichVu($link,"Đại học");
ThemDichVu($link,"Dịch vụ ăn uống");
ThemDichVu($link,"Dịch vụ chăm sóc bệnh tại nhà");
ThemDichVu($link,"Dịch vụ chăm sóc sau sinh tại nhà");
ThemDichVu($link,"Dịch vụ chuyển nhà trọn gói");
ThemDichVu($link,"Dịch vụ làm đẹp tại nhà: Móng");
ThemDichVu($link,"Dịch vụ làm đẹp tại nhà: Tóc");
ThemDichVu($link,"Dịch vụ làm đẹp tại nhà: Trang điểm");
ThemDichVu($link,"Dịch vụ pháp lý tại nhà");
ThemDichVu($link,"Dịch vụ pháp lý");
ThemDichVu($link,"Dịch vụ sửa chăm sóc xe hơi tại nhà");
ThemDichVu($link,"Dịch vụ sửa chữa bảo dưỡng máy lạnh tại nhà");
ThemDichVu($link,"Dịch vụ sửa chữa bảo dưỡng thiết bị điện tử gia đình tại nhà");
ThemDichVu($link,"Dịch vụ sửa chữa điện nước tại nhà");
ThemDichVu($link,"Dịch vụ tư vấn pháp luật ở nhà");
ThemDichVu($link,"Điện thoại/Máy tính/Laptop");
ThemDichVu($link,"Du lịch");
ThemDichVu($link,"Dụng cụ/thiết bị công trình xây dựng cho thuê");
ThemDichVu($link,"Game");
ThemDichVu($link,"Gia sư tại nhà");
ThemDichVu($link,"Giải trí");
ThemDichVu($link,"Giao hàng");
ThemDichVu($link,"Giặt Thảm / Giường / Nệm / Rèm / ở nhà");
ThemDichVu($link,"Giúp việc nhà");
ThemDichVu($link,"Hàng điện tử");
ThemDichVu($link,"Hàng rong");
ThemDichVu($link,"Hạt giống");
ThemDichVu($link,"Hiệu cắt tóc");
ThemDichVu($link,"Hồ bơi");
ThemDichVu($link,"Hóa học");
ThemDichVu($link,"Home Stay theo ngày");
ThemDichVu($link,"Huấn luyện viên Thể dục - Thể thao");
ThemDichVu($link,"Hướng dẫn viên");
ThemDichVu($link,"Hút hầm cầu");
ThemDichVu($link,"Karaoke");
ThemDichVu($link,"Khách sạn 01 sao");
ThemDichVu($link,"Khách sạn 02 sao");
ThemDichVu($link,"Khách sạn 03 sao");
ThemDichVu($link,"Khách sạn 04 sao");
ThemDichVu($link,"Khách sạn 05 sao");
ThemDichVu($link,"Khách sạn không đánh sao");
ThemDichVu($link,"Khu giải trí cho trẻ em");
ThemDichVu($link,"Làm đẹp");
ThemDichVu($link,"Lều/trại - Túi ngủ - Võng");
ThemDichVu($link,"Mát Xa Tại Nhà");
ThemDichVu($link,"Mẹ và bé");
ThemDichVu($link,"Móng");
ThemDichVu($link,"Nấu tiệc tại nhà");
ThemDichVu($link,"Ngôn ngữ học");
ThemDichVu($link,"Nhà / biệt thự cho thuê theo ngày");
ThemDichVu($link,"Nhà / biệt thự cho thuê theo tháng");
ThemDichVu($link,"Nhà hàng");
ThemDichVu($link,"Nha sĩ");
ThemDichVu($link,"Nhà trẻ");
ThemDichVu($link,"Nhân viên tiếp thị");
ThemDichVu($link,"Nước giải khát");
ThemDichVu($link,"Phân bón");
ThemDichVu($link,"Phòng cho thuê theo giờ");
ThemDichVu($link,"Phòng cho thuê theo ngày");
ThemDichVu($link,"Phòng cho thuê theo tháng");
ThemDichVu($link,"Phòng dạy Thiền");
ThemDichVu($link,"Phòng dạy võ");
ThemDichVu($link,"Phòng dạy Yoga");
ThemDichVu($link,"Phòng GYM");
ThemDichVu($link,"Phụ Kiện Thời Trang");
ThemDichVu($link,"Quán ăn gia đình");
ThemDichVu($link,"Quán bar");
ThemDichVu($link,"Quán cà phê");
ThemDichVu($link,"Rao vặt: Đất bán");
ThemDichVu($link,"Rao vặt: Điện thoại/Máy tính/Laptop");
ThemDichVu($link,"Rao vặt: đồ gỗ");
ThemDichVu($link,"Rao vặt: máy quay phim, chụp hình");
ThemDichVu($link,"Rao vặt: Nhà bán");
ThemDichVu($link,"Rao vặt: xe hơi cũ");
ThemDichVu($link,"Rao vặt: xe máy cũ");
ThemDichVu($link,"Rạp chiếu phim");
ThemDichVu($link,"Rau");
ThemDichVu($link,"Rượu");
ThemDichVu($link,"Sân Cầu lông");
ThemDichVu($link,"Sân Quần vợt");
ThemDichVu($link,"Siêu thị");
ThemDichVu($link,"Sinh vật học");
ThemDichVu($link,"Spa");
ThemDichVu($link,"Sử");
ThemDichVu($link,"Sửa chữa và bảo dưỡng xe hơi lưu động");
ThemDichVu($link,"Sửa chữa và bảo dưỡng xe máy lưu động");
ThemDichVu($link,"Sức khỏe");
ThemDichVu($link,"Tài xế");
ThemDichVu($link,"Tạp hóa");
ThemDichVu($link,"Taxi");
ThemDichVu($link,"Thám tử tư");
ThemDichVu($link,"Thể thao");
ThemDichVu($link,"Thiết kế nội thất");
ThemDichVu($link,"Thiết kế và thi công quản cáo");
ThemDichVu($link,"Thợ gỗ");
ThemDichVu($link,"Thợ hồ");
ThemDichVu($link,"Thợ may");
ThemDichVu($link,"Thời trang");
ThemDichVu($link,"Thú cưng");
ThemDichVu($link,"Thú y");
ThemDichVu($link,"Thừa phát lại");
ThemDichVu($link,"Thức ăn đông lạnh");
ThemDichVu($link,"Thức ăn gia súc, gia cầm");
ThemDichVu($link,"Thực phẩm biển");
ThemDichVu($link,"Thực phẩm chưa chế biến");
ThemDichVu($link,"Thức uống");
ThemDichVu($link,"Thuốc bảo vệ thực vật");
ThemDichVu($link,"Tiệm Giặt ủi");
ThemDichVu($link,"Tiệm sửa chữa và bảo dưỡng xe hơi");
ThemDichVu($link,"Tiệm sửa chữa và bảo dưỡng xe máy");
ThemDichVu($link,"Tiệm thuốc");
ThemDichVu($link,"Tổ chức sự kiệ");
ThemDichVu($link,"Toán học");
ThemDichVu($link,"Tóc");
ThemDichVu($link,"Trái cây");
ThemDichVu($link,"Trạm xá");
ThemDichVu($link,"Trang Điểm");
ThemDichVu($link,"Trồng rau sạch tại nhà");
ThemDichVu($link,"Trông trẻ em");
ThemDichVu($link,"Trung tâm gia sư");
ThemDichVu($link,"Trung tâm ngoại ngữ");
ThemDichVu($link,"Trường cấp 1");
ThemDichVu($link,"Trường cấp 2");
ThemDichVu($link,"Trường cấp 3");
ThemDichVu($link,"Trường");
ThemDichVu($link,"Vận chuyển");
ThemDichVu($link,"Văn học");
ThemDichVu($link,"Văn phòng công chứng");
ThemDichVu($link,"Văn phòng dịch thuật");
ThemDichVu($link,"Văn phòng hướng dẫn viên");
ThemDichVu($link,"Văn phòng luật sư");
ThemDichVu($link,"Vật lý học");
ThemDichVu($link,"Vệ sĩ");
ThemDichVu($link,"Vé tàu xe máy bay");
ThemDichVu($link,"Xăng");
ThemDichVu($link,"Xây dựng");
ThemDichVu($link,"Xe ba bánh");
ThemDichVu($link,"Xe cho thuê");
ThemDichVu($link,"Xe cộ");
ThemDichVu($link,"Xe công trình xây dựng cho thuê");
ThemDichVu($link,"Xe đạp");
ThemDichVu($link,"Xe hơi bảy chổ");
ThemDichVu($link,"Xe hơi bốn chổ");
ThemDichVu($link,"Xe khách nhỏ");
ThemDichVu($link,"Xe khách");
ThemDichVu($link,"Xe máy");
ThemDichVu($link,"Xe ôm");
ThemDichVu($link,"Xe tải");
ThemDichVu($link,"Xét nghiệm tại nhà");

echo "Hoàn tất cập nhật danh sách dịch vụ";
//--------------------------------------------------
 mysqli_close($link);
// function
function ThemVung($link, $ten, $dt) {

	$sql = "INSERT INTO VUNG (TENVUNG, DIENTICH) VALUES ('$ten','$dt')";

	if(!mysqli_query($link, $sql)){
		echo '<br> ERROR: ' . mysqli_error($link);
 	}
 }
 function ThemDichVu($link, $ten) {

	$sql = "INSERT INTO DICHVU (TENDICHVU) VALUES ('$ten')";

	if(!mysqli_query($link, $sql)){
		echo '<br> ERROR: ' . mysqli_error($link);
 }
}
?>
